[package]
name = "rust_experiments"
authors = ["Alexander Öberg"]
version = "0.1.0"
edition = "2021"
publish = false
build = "build/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_experiments_lib"
path = "src/lib.rs"

[[bin]]
name = "rust_experiments"
path = "src/main.rs"

[dependencies]
rayon = "1.10.0"
zstd = "0.13.3"
scrap = "0.5.0"
crossterm = "0.28.1"
crc32fast = "1.4.2"
xxhash-rust = {version = "0.8.15", features = ["xxh3"]}
tui = "0.19.0"
rand = "0.9.0"

[dev-dependencies]
criterion = "0.5.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[build-dependencies]
zstd = "0.13.3"
toml = "0.8.20"
serde = { version = "1.0.219", features = ["derive"] }
chrono = "0.4.40"
crc32fast = "1.4.2"
xxhash-rust = {version = "0.8.15", features = ["xxh3"]}

[[bench]]
name = "benchmark"
harness = false